# Generated by Django 4.2.5 on 2023-09-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('models', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='All_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('registration_no', models.IntegerField()),
                ('chassis_no', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('manufacturing_year', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.model')),
            ],
        ),
    ]
