# Generated by Django 4.2.5 on 2023-09-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_all_detail_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='all_detail',
            name='registration_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
