# Generated by Django 4.2.5 on 2023-09-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_all_detail_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='car_x_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_work', models.FileField(upload_to='before work/')),
                ('date', models.DateField(auto_now_add=True)),
                ('estimate', models.IntegerField()),
                ('remarks', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.all_detail')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.work')),
            ],
        ),
    ]
