# Generated by Django 4.2.5 on 2023-10-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_car_x_mod_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_x_mod',
            name='car',
        ),
        migrations.RemoveField(
            model_name='car_x_mod',
            name='work',
        ),
        migrations.DeleteModel(
            name='All_Detail',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='car_x_mod',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
