# Generated by Django 4.2.5 on 2023-10-01 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0006_remove_car_x_mod_car_remove_car_x_mod_work_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Detail',
            fields=[
                ('registration_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('chassis_no', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('manufacturing_year', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('models', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='final_settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_work', models.FileField(upload_to='before work/')),
                ('after_work', models.FileField(upload_to='after work/')),
                ('estimate', models.IntegerField()),
                ('Final_cost', models.IntegerField()),
                ('remarks', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.all_detail')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.work')),
            ],
        ),
        migrations.CreateModel(
            name='car_x_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('before_work', models.FileField(upload_to='before work/')),
                ('estimate', models.IntegerField()),
                ('remarks', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.all_detail')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.work')),
            ],
        ),
        migrations.AddField(
            model_name='all_detail',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car'),
        ),
        migrations.AddField(
            model_name='all_detail',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.model'),
        ),
    ]
