# Generated by Django 4.2.5 on 2023-10-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_x_mod',
            name='date',
        ),
    ]
