# Generated by Django 4.2.5 on 2023-10-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_car_x_mod_date_remove_final_settlement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_settlement',
            name='before_work',
        ),
    ]
